### ISSUE TITLE
Projector Calibration

### ISSUE THREAD

**Issue by Quma233** [uzh-rpg/ESL#2]
Hi @Manasi94 , thanks for your inspiring work! I am trying to reproduce the result on the newly collected data, but I am not sure how the projector is calibrated. If possible, could you please provide some details about it?

**Comment by Quma233** [comment]
According to the information provided in the paper, I presume that you used a blinking stripe pattern to excite the EVENT, and used E2VID to recover the grayscale maps with the stripe, which are then fed to the calibration software, is that right? Thanks for your help!

**Comment by Manasi94** [comment]
For calibrating the projector, I use the blinking strip pattern to trigger events. 
The events caused by each pattern are converted to event-frame representation. (when an event occurs at x,y the corresponding pixel in the event-frame representation is assigned value 1). This results in binary images corresponding to the stripe pattern.
These images are then used to calibrate the projector using traditional SL calibration.

E2VID is only used for calibrating the event camera, not for calibrating the projector.

**Comment by Quma233** [comment]
I noticed that, in the calibration file provided, despite the reprojection error of the projector is around 3.6 pixels, ESL is still able to make a good 3D reconstruction. I wonder, for ESL, how much reprojection error is usually needed to keep the projector within in order to get a good reconstruction, is it necessary to keep the reprojection error of the projector to within 1?

**Comment by Manasi94** [comment]
In our case the projector has a higher resolution as compared to the event camera. Since the calibration uses events-frame representation, the calibration is limited by the spatial resolution difference between the event camera and projector. Therefore, we could not achieve any lower reprojection error within 1 pixel.
